version: '3'

services:
  # Database service
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: devuser
      POSTGRES_DB: microservices_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API service
  api:
    build: ./easy_3tire_js_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://devuser:devpassword@db:5432/microservices_db
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./easy_3tire_js_api:/app
      - /app/node_modules
    command: npm run dev

  # Spring Boot API service
  springboot-api:
    build: ./easy_3tire_springboot_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservices_db
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
    ports:
      - "8081:8080"
    volumes:
      - ./easy_3tire_springboot_api:/app

  # Frontend service
  frontend:
    build: ./easy_3tire_js_frontend
    depends_on:
      - api
      - springboot-api
    environment:
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_SPRINGBOOT_API_URL: http://localhost:8081
      PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./easy_3tire_js_frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  db-data: